### ISSUE TITLE
Steps to clean-up  /digital strategy page

### ISSUE THREAD

**Issue by mboone** [GSA/gsa.github.io#28]
1. Take off additional tabs in middle of the page - Open Data, background & developer resources
2. Add Joe's contact information under Sonny's as:
   >>Joseph Castle 
   >>GSA IT Lead for Digital Innovation and Strategy
   >>joseph.castle@gsa.gov
3. Add link to Developer Resources (Github page)  in box labelled "Open Data" on right  
4. Change GSA.gov/Data link to new open.gsa.gov/data Github page
5. Remove all text including and below "Open Data Publication Process" and link a downloaded version of  this document in "Open Data" box to the right https://docs.google.com/a/gsa.gov/document/d/1yOZ9O-d_Ps7khzhIdt6ymOvt4Cr3w0brKg-APHT5Pt8/edit?usp=sharing 
6. Remove box labelled "LINKs" in right panel

@gbinal @JSGGSA

**Comment by mpan905** [comment]
1. Do you need to retain the three tab pages? We can either "take off" the additional tabs by turning them into standard child pages (they will still be online and available via search and direct links) or just take them completely offline.

Here's what it would look like if we changed the presentation:
Overview:
![screen shot 2015-02-24 at 4 41 40 pm](https://cloud.githubusercontent.com/assets/4094807/6359984/c2991796-bc44-11e4-9fe4-edfff077ce4b.png)
Child page:
![screen shot 2015-02-24 at 4 45 15 pm](https://cloud.githubusercontent.com/assets/4094807/6360003/dcd22882-bc44-11e4-84c3-84e3f9ad3121.png)

Two) On staging
Three) On staging
Four) Can't stage this. This will need to be done when everything goes live.
Five) On staging. I turned the content into a word doc in the file manager since the google doc is only shared with users within gsa.gov. 
Six) On staging.

*Sorry for the numbering. It keeps automatically renumbering from the beginning so this was the easy way around it

**Comment by mboone** [comment]
The Open Data Schedule information, should remain on the /digitalstrategy page (done in staging). You can remove the tab labelled "open data" and just keep the information. 

Let's keep the background tab as a child page (but still remove the tab from /digitalstrategy page) until I can review to determine if content resides elsewhere.

#3. I don't see the link to /developer page in the "Open Data" box to the right
#6. The box labelled "Related links" in right panel has not been removed

**Comment by mboone** [comment]
Changes made to satisfaction. Will open new issue with revisions.
